name: watermark_camera
description: "A watermark camera app built with Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Camera & Media
  camera: ^0.11.0+2
  video_player: ^2.8.1
  video_compress: ^3.1.3
  photo_manager: ^3.6.1
  gal: ^2.3.0
  extended_image: ^8.3.0
  widgets_to_image: ^1.0.0
  pro_image_editor: ^6.1.3
  just_audio: ^0.9.42
  sound_mode: ^3.0.0
  ffmpeg_kit_flutter_min: ^6.0.3
  chewie: ^1.8.5
  wechat_assets_picker: ^9.4.1
  mime: ^2.0.0
  image: ^4.0.17
  audioplayers: ^6.4.0
  # flutter_ffmpeg: ^0.4.2

  # UI Components
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2
  flutter_colorpicker: ^1.1.0
  flutter_popup: ^3.3.0
  dotted_border: ^2.1.0
  roundcheckbox: ^2.0.4+1
  animate_do: ^3.3.4
  flutter_picker_plus: ^1.3.0
  cupertino_icons: ^1.0.2
  flutter_arc_text: ^0.6.0
  google_fonts: ^6.2.1
  flutter_easyloading: ^3.0.5

  # State Management & Navigation
  get: ^4.6.6

  # Storage & Files
  path_provider: ^2.1.3
  better_open_file: ^3.6.5
  shared_preferences: ^2.2.3
  flutter_dotenv: ^5.1.0
  sqflite: ^2.4.1

  # Network & API
  dio: ^5.5.0+1
  webview_flutter: ^4.8.0
  http_parser: ^4.1.2
  flutter_client_sse: ^2.0.3

  # Permissions & Location
  permission_handler: ^11.3.1
  amap_flutter_location: ^3.0.0
  geolocator: ^13.0.2

  # Utils
  archive: ^3.6.1
  collection: ^1.17.2
  cross_file: ^0.3.4+1
  date_format: ^2.0.7
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  lunar: ^1.7.0
  uuid: ^4.4.2
  share_plus: ^10.1.2
  vibration: ^2.0.1
  flutter_keyboard_visibility: ^6.0.0
  mask_text_input_formatter: ^2.9.0
  sprintf: ^7.0.0
  package_info_plus: ^8.1.1
  crypto: ^3.0.6
  flutter_localization: ^0.3.1
  flutter_baidu_mapapi_map: ^3.9.0
  qr_flutter: ^4.1.0
  fluwx: ^5.4.1
  flutter_compass: ^0.8.1

  # Payment
  alipay_kit: ^6.0.0
  pull_to_refresh: ^2.0.0
  path: ^1.9.0
  exif: ^3.3.0

dependency_overrides:
  uuid: ^4.4.2
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  extended_image: ^8.3.0
  camera: ^0.11.0+2

alipay_kit: #scheme 是支付宝 SDK 用来实现支付完成后从支付宝 App 跳回你的 App 的机制
  scheme: alipay9021000144612694

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/images/
    - assets/webp/
    - assets/html/
    - assets/media/
    - assets/vip/
    - .env
